name            : example
description     : Example project for spring_button.
version         : 1.0.12
author          : Ali Yigit Bireroglu <aliyigitbireroglu@gmail.com>
repository      : https://github.com/aliyigitbireroglu/flutter-spring-button
homepage        : https://www.cosmossoftware.coffee

environment     :
  sdk: ">=2.1.0 <3.0.0"

dependencies    :
  flutter      :
    sdk: flutter
  spring_button:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter         :
  uses-material-design: true
